### ISSUE TITLE
omex locations and rdf:about should be identical

### ISSUE THREAD

**Issue by matthiaskoenig** [SemsProject/CombineArchiveShowCase#4]
I am trying to read the RDF annotations with libCombine of the CombineArchiveShowcase.
Unfortunately, these cannot be read because the rdf:about are different than the location.
libcombine & also other libraries reading Omex assume that the locations are identical.

The specification states that these should be identical
"
COMBINE archive can include multiple metadata elements adding information about different content files. To
identify the file a metadata element refers to, the rdf:about attribute of the relevant metadata structure
**should use the same value as used in the location attribute of the respective Content element, e.g.**
"
=> please make the location and rdf:about identical
=> also this should be change to "must be identical" in the next specification

**Comment by binfalse** [comment]
this is fixed with #6
